# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ----------------------------------------------------------------------------
# Site settings
# ----------------------------------------------------------------------------
title: gone with wind
brief-intro: Cogito ergo sum，思想因为真实而虚伪
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhaolj214.github.io/wiki/" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# ----------------------------------------------------------------------------
# other links
# ----------------------------------------------------------------------------
twitter_username: jimoshutong
facebook_username: 若水三千
github_username:  zhaolj214
email: jimoshutong#163.com, jimoshutong#gmail.com
weibo_username: zhaolj214
zhihu_username: zhaolj214
linkedIn_username:
dribbble_username:

description_footer:

# ----------------------------------------------------------------------------
# comments
# two ways to comment, only choose one, and use your own short name
# ----------------------------------------------------------------------------
# duoshuo_shortname: 
disqus_shortname:

# ----------------------------------------------------------------------------
# statistic analysis
# Baidu statistics ID, the statistical code is replaced by your own id which you can apply for
# one from website 'https://tongji.baidu.com'
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# ----------------------------------------------------------------------------
baidu_tongji_id: 2ce90c2b5ead6572dfa5bfb89a3ca4a8
#google_analytics_id: UA-72449510-4 # google 分析追踪id

# ----------------------------------------------------------------------------
# Build settings
# ----------------------------------------------------------------------------
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# ----------------------------------------------------------------------------
# port
# ----------------------------------------------------------------------------
# port: 80

# ----------------------------------------------------------------------------
# url
# ----------------------------------------------------------------------------
category_dir: category/
tag_dir: tag/

# ----------------------------------------------------------------------------
# excerpt
# ----------------------------------------------------------------------------
excerpt_separator: "\n\n\n\n"

# ----------------------------------------------------------------------------
# paginate
# ----------------------------------------------------------------------------
gems: [jekyll-paginate]
paginate: 10
